[programs.localnet]
tutorial = "FdjuHUPyrqsdY9nQzGE8WzZfjMwUyutAMbTCgEtwCgPe"

[programs.devnet]
tutorial = "FdjuHUPyrqsdY9nQzGE8WzZfjMwUyutAMbTCgEtwCgPe"

[programs.mainnet]
tutorial = "FdjuHUPyrqsdY9nQzGE8WzZfjMwUyutAMbTCgEtwCgPe"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/oli/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
copy-idl = "mkdir -p web/src/idl && cp target/idl/tutorial.json web/src/idl/tutorial.json"
