[programs.localnet]
tutorial = "9Je1KH27W4ARK8F5RSk5ZuDfgwEPgarggzwHdSrgFmBC"

[programs.devnet]
tutorial = "9Je1KH27W4ARK8F5RSk5ZuDfgwEPgarggzwHdSrgFmBC"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/oli/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
